### ISSUE TITLE
Create a Responsive Navbar in index.html

### ISSUE THREAD

**Issue by ijaz-ali-dev** [CharakRaman/hackoctober2K22#46]
Sir am very hardworking on this issue so please accept my request.

**Comment by ijaz-ali-dev** [comment]
I will create a navbar as your requirement

**Comment by Prameet-Kumar** [comment]
May you please assign this task to me? I would be very thankful to you.

**Comment by m-mishra2001** [comment]
@CharakRaman please assign me this issue
